[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
description = "ABC"
[tool.poetry.dependencies]
"discord.py" = "^1.6"
python = "^3.8"
flask = "^1.1"
tinydb = "^4.4.0"
unidecode = "^1.2.0"
tabulate = "^0.8.9"
