[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
description = "ABC"
[tool.poetry.dependencies]
"discord.py" = "^1.3.4"
python = "^3.8"
flask = "^1.1"
lxml = "^4.5.2"
